name: CI Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Allows you to run this workflow from another workflow
  workflow_call:

jobs:
  build:
    steps:
      - uses: AustinEast/echo/.github/composites/build@master
