name: CI Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Allows you to run this workflow from another workflow
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: krdlab/setup-haxe@v1
      - uses: actions/checkout@v2
        with:
          haxe-version: 4.2.4
          
      - name: Install Haxelib Dependencies
        run: |
          haxelib git dox https://github.com/HaxeFoundation/dox.git
          haxelib git heaps https://github.com/HeapsIO/heaps.git
          haxelib dev echo .
          
      - name: Run Builds
        run: |
          haxe test.hxml
          haxe sample.hxml
          haxe dox.hxml
