name: Deploy

# Controls when the workflow will run
on:
#   release:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-build:
    uses: AustinEast/echo/.github/workflows/build.yml@v1

  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get Joke Of The Day
        uses: h2floh/action-get-joke-of-the-day@v1

