# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        haxe: [4.2.4]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe }}
      - run: haxe -version
      - run: haxelib git dox https://github.com/HaxeFoundation/dox.git
      - run: haxelib git heaps https://github.com/HeapsIO/heaps.git
      - run: haxelib dev echo .
      - run: haxe ./test.hxml
      - run: haxe ./sample.hxml
      - run: haxe ./dox.hxml
