name: Release

# Controls when the workflow will run
on:
#   release:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    name: Build Artifacts
    uses: AustinEast/echo/.github/workflows/build.yml@master

  deploy-website:
    name: Deploy to Github Pages
    needs: build
    runs-on: ubuntu-latest
    steps:      
      - name: Download Website Artifact
        uses: actions/download-artifact@v2
        with:
          name: echo-web
  
      - name: Unzip Website Artifact
        run: unzip echo-web.zip
      
      - name: Deploy Artifact
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-haxelib:
    name: Deploy to Haxelib
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: krdlab/setup-haxe@v1
    
      - name: Download Haxelib Artifact
        uses: actions/download-artifact@v2
        with:
          name: echo-haxelib

      - name: Deploy Artifact
        run: haxelib submit echo-haxelib.zip ${{ secrets.HAXELIB_PWD }} --always
